### ISSUE TITLE
Upgrade to material-ui@0.16.7

### ISSUE THREAD

**Issue by JeremyIglehart** [Zetoff/accounts-material-ui#25] opened 2017-01-26 07:45 UTC
Getting this warning:

```
W20170126-02:42:41.020(-5)? (STDERR) WARNING: npm peer requirements (for zetoff:accounts-material-ui) not installed:
W20170126-02:42:41.020(-5)? (STDERR)  - material-ui@0.16.7 installed, material-ui@0.15.4 needed
```

Is there an easy workaround while we wait to catch up to the new version?

Is there a reason we can't use `material-ui@0.16.7` now?

Edit: This is just an annoying warning, it actually still works without any problem (other than the annoying warnings)

**Comment by PolGuixe** [comment] 2017-02-07 16:16
@JeremyIglehart are you still having problems? It should work with any version of material-ui fulfilling this [requirement](https://github.com/Zetoff/accounts-material-ui/blob/develop/check_npm.js#L3):
```
  'material-ui': '>=0.16.x'
```
 Which version of the package are you using?

**Comment by PolGuixe** [comment] 2017-02-19 01:45
@JeremyIglehart have you got any chance to test it? 

I am closing the issue, if the problem is persistent let me know.

**Closed as completed by PolGuixe** 2017-02-19 01:45 UTC
